export const English = {
  incomming: "Incomming",
  outgoing: "Outgoing",
  addRecord: "Add Record",
  id: "ID",
  recordName: "Record Name",
  recipientOrg: "Recipient Organization",
  referenceNumber: "Reference Number",
  dateOfDispatch: "Date Of Dispatch",
  deliveryPersonnel: "Delivery Personnel",
  subject: "Subject",
  actions: "Actions",
  uploadRecord: "Upload Record",
  cancel: "Cancel",
  submit: "Submit",
  editRecord: "Edit Record",
  viewRecord: "View Record",
  fileName: "File Name",
  remark: "Remark",
  detail: "Detail",
  addRemark: "Add Remark",
  title: "Title",
  listRemarks:"Remarks List"
};

export const AMHARIC = {
  incomming: "ገቢ",
  outgoing: "ወጪ",
  addRecord: "መዝገብ",
  id: "ID",
  recordName: "የመዝገብ ስም",
  recipientOrg: "ተቀባይ ተቋም",
  referenceNumber: "የማጣቀሻ ቁጥር",
  dateOfDispatch: "የተላከበት ቀን",
  deliveryPersonnel: "ያደረሰው ስራተኛ",
  subject: "ርዕሰ ጉዳይ",
  actions: "ድርጊቶች",
  uploadRecord: "",
  cancel: "",
  submit: "አስገባ",
  editRecord: "",
  viewRecord:"",
  fileName: "የመዝገብ ስም",
  remark: "AM_Remark",
  detail: "AM_Detail",
  title:"AM_Title",
  addRemark: "AM_add Remark",
  listRemarks:"AM_Remarks List"
};
