export const English = {
  incomming: "Incomming",
  outgoing: "Outgoing",
  addRecord: "Add Record",
  id: "ID",
  recordName: "Record Name",
  recipientOrg: "Recipient Organization",
  referenceNumber: "Reference Number",
  dateOfDispatch: "Date Of Dispatch",
  deliveryPersonnel: "Delivery Personnel",
  subject: "Subject",
  actions: "Actions",
  uploadRecord: "Upload Record",
  cancel: "Cancel",
  submit: "Submit",
  editRecord: "Edit Record",
  fileName: "File Name",
};

export const AMHARIC = {
  incomming: "ገቢ",
  outgoing: "ወጪ",
  addRecord: "መዝገብ",
  id: "ID",
  recordName: "የመዝገብ ስም",
  recipientOrg: "ተቀባይ ተቋም",
  referenceNumber: "የማጣቀሻ ቁጥር",
  dateOfDispatch: "የተላከበት ቀን",
  deliveryPersonnel: "ያደረሰው ስራተኛ",
  subject: "ርዕሰ ጉዳይ",
  actions: "ድርጊቶች",
  uploadRecord: "",
  cancel: "",
  submit: "አስገባ",
  editRecord: "",
  fileName: "የመዝገብ ስም",
};
