export const English = {
  incomming: "Incoming",
  outgoing: "Outgoing",
  addRecord: "Add Record",
  id: "Id",
  recordName: "Record Name",
  recipientOrg: "Recipient Organization",
  referenceNumber: "Reference Number",
  dateOfDispatch: "Date Of Dispatch",
  receievingPersonnel: "Receiving Personnel",
  subject: "Subject",
  actions: "Actions",
  uploadRecord: "Add Outgoing Record",
  uploadIncomingRecord: "Add Incoming Record",
  cancel: "Cancel",
  submit: "Save",
  editRecord: "Edit Outgoing Record",
  editIncomingRecord: "Edit Incoming Record",
  viewRecord: "View Record",
  fileName: "File Name",
  remark: "Remarks",
  detail: "Detail",
  addRemark: "Add Remark",
  title: "Title",
  listRemarks: "Remarks List",
  page: "Page",
  prev: "Prev",
  next: "Next",
  search: "Search",
  IncomingRecordDate: "Incoming Record Received Date",
  senderOrg: "Sender Organization",
  location: "Location",
  fillRecordInfo: "Fill Record Information",
  selectLocation: "select location",
  file: "File",
  uploadSuccess: "Uploaded Successfully",
  updateSuccess: "Updated Successfully",
  inputsError: "Please fill the required fields",
  remarkAddSuccess: "Remark Added Successfully",
  haveAccessToFile: "Have access to file?",
  stnWentWrong: "Something went wrong",
  inputfileName: "File Name",
  refNumberError: "Reference Number is required",
  subjectError: "Subject is required",
  sendingOrgNameError: "Sending Organization Name is required",
  incomingDateError: "Incoming Record date is required",
  reciepientOrgNameError: "Recipient Organization is required",
  dispatchDateError: "Date of dispatch is required",
  fileError: "File is required",
};

export const AMHARIC = {
  incomming: "ገቢ",
  outgoing: "ወጪ",
  addRecord: "አዲስ መዝግብ",
  id: "መለያ",
  recordName: "የመዝገብ ስም",
  recipientOrg: "ተቀባይ ተቋም",
  referenceNumber: "የማጣቀሻ ቁጥር",
  dateOfDispatch: "የተላከበት ቀን",
  receievingPersonnel: "የተቀበለው ስራተኛ",
  subject: "ርዕሰ ጉዳይ",
  actions: "ድርጊቶች",
  uploadRecord: "ወጪ መዝገብ አስገባ",
  uploadIncomingRecord: "ገቢ መዝገብ አስገባ",
  cancel: "አቋርጥ",
  submit: "አስገባ",
  editRecord: "ወጪ አስተካክል",
  editIncomingRecord: "ገቢ አስተካክል",
  viewRecord: "መዝገብ ተመልከት",
  fileName: "የመዝገብ ስም",
  remark: "ይዘት",
  detail: "AM_Detail",
  title: "ርእስ",
  addRemark: "ይዘት ጨምር",
  listRemarks: "የይዘት ዝርዝር",
  page: "ገጽ",
  prev: "በፊት",
  next: "ቀጣይ",
  search: "ፈልግ",
  IncomingRecordDate: "የገቢ መዝገብ የገባበት የቀን",
  senderOrg: "የላኪ ድርጅት ስም",
  location: "ቦታ",
  fillRecordInfo: "የመዝገብ መረጃን ሙላ",
  selectLocation: "ቦታ ይምረጡ",
  file: "ፋይል",
  uploadSuccess: "ተሳክቷል",
  updateSuccess: "ተሳክቷል",
  inputsError: "እባክዎ አስፈላጊዎቹን ቅጾች ይሙሉ",
  haveAccessToFile: "ፋይሉ አለዎት?",
  remarkAddSuccess: "ይዘት በተሳካ ሁኔታ ታክሏል። ",
  inputfileName: "የፋይል ስም",
  refNumberError: "የማጣቀሻ ቁጥር አልተሞላም",
  subjectError: "ርዕሰ ጉዳይ አልተሞላም",
  sendingOrgNameError: "የላኪ ድርጅት ስም አልተሞላም",
  incomingDateError: "መዝገብ የገባበት የቀን አልተሞላም",
  reciepientOrgNameError: "የተቀባይ ድርጅት ስም አልተሞላም",
  dispatchDateError: "መዝገብ የተላከበት ቀን አልተሞላም",
  fileError: "ፋይል አልተሞላም",
};
